INSERT INTO Genre VALUES(1,'Action');
INSERT INTO Genre VALUES(2,'Adventure');
INSERT INTO Genre VALUES(3,'Drama');
INSERT INTO Genre VALUES(4,'Fantasy');
INSERT INTO Genre VALUES(5,'Sci-Fi');
INSERT INTO Genre VALUES(6,'Suspense');
INSERT INTO Genre VALUES(7,'Supernatural');
INSERT INTO Genre VALUES(8,'Award Winning');
INSERT INTO Genre VALUES(9,'Romance');
INSERT INTO Genre VALUES(10,'Comedy');
INSERT INTO Genre VALUES(11,'Sports');
INSERT INTO Genre VALUES(12,'Mystery');
INSERT INTO Genre VALUES(13,'Slice of Life');
INSERT INTO Genre VALUES(14,'Avant Garde');
INSERT INTO Genre VALUES(15,'Horror');
INSERT INTO Genre VALUES(16,'Ecchi');
INSERT INTO Genre VALUES(17,'Gourmet');
INSERT INTO Genre VALUES(18,'Boys Love');
INSERT INTO Genre VALUES(19,'Girls Love');