INSERT INTO Theme VALUES(1,'Military');
INSERT INTO Theme VALUES(2,'Gore');
INSERT INTO Theme VALUES(3,'Survival');
INSERT INTO Theme VALUES(4,'Psychological');
INSERT INTO Theme VALUES(5,'Time Travel');
INSERT INTO Theme VALUES(6,'Romantic Subtext');
INSERT INTO Theme VALUES(7,'Mecha');
INSERT INTO Theme VALUES(8,'Super Power');
INSERT INTO Theme VALUES(9,'Mythology');
INSERT INTO Theme VALUES(10,'School');
INSERT INTO Theme VALUES(11,'Music');
INSERT INTO Theme VALUES(12,'Adult Cast');
INSERT INTO Theme VALUES(13,'Space');
INSERT INTO Theme VALUES(14,'Historical');
INSERT INTO Theme VALUES(15,'Parody');
INSERT INTO Theme VALUES(16,'Team Sports');
INSERT INTO Theme VALUES(17,'Childcare');
INSERT INTO Theme VALUES(18,'Organized Crime');
INSERT INTO Theme VALUES(19,'Samurai');
INSERT INTO Theme VALUES(20,'Gag Humor');
INSERT INTO Theme VALUES(21,'Isekai');
INSERT INTO Theme VALUES(22,'Reincarnation');
INSERT INTO Theme VALUES(23,'Detective');
INSERT INTO Theme VALUES(24,'Mahou Shoujo');
INSERT INTO Theme VALUES(25,'Delinquents');
INSERT INTO Theme VALUES(26,'Workplace');
INSERT INTO Theme VALUES(27,'Vampire');
INSERT INTO Theme VALUES(28,'Martial Arts');
INSERT INTO Theme VALUES(29,'Otaku Culture');
INSERT INTO Theme VALUES(30,'Showbiz');
INSERT INTO Theme VALUES(31,'Love Polygon');
INSERT INTO Theme VALUES(32,'High Stakes Game');
INSERT INTO Theme VALUES(33,'Iyashikei');
INSERT INTO Theme VALUES(34,'Combat Sports');
INSERT INTO Theme VALUES(35,'Strategy Game');
INSERT INTO Theme VALUES(36,'Visual Arts');
INSERT INTO Theme VALUES(37,'Crossdressing');
INSERT INTO Theme VALUES(38,'Reverse Harem');
INSERT INTO Theme VALUES(39,'CGDCT');
INSERT INTO Theme VALUES(40,'Anthropomorphic');
INSERT INTO Theme VALUES(41,'Harem');
INSERT INTO Theme VALUES(42,'Video Game');
INSERT INTO Theme VALUES(43,'Racing');
INSERT INTO Theme VALUES(44,'Performing Arts');
INSERT INTO Theme VALUES(45,'Idols (Female)');
INSERT INTO Theme VALUES(46,'Idols (Male)');
INSERT INTO Theme VALUES(47,'Educational');
INSERT INTO Theme VALUES(48,'Medical');
INSERT INTO Theme VALUES(49,'Magical Sex Shift');
INSERT INTO Theme VALUES(50,'Pets');
INSERT INTO Theme VALUES(51,'Memoir');
INSERT INTO Theme VALUES(52,'Villainess');